### ISSUE TITLE
cloudformation(cfn)のtips

### ISSUE THREAD

**Issue by owari-taro** [owari-taro/sphinx_docs#3]
## if で複数属性の設定

```
         ResourceRequirements: 
                  - Type: VCPU
                    Value: !Ref VCPU
                  - Type: MEMORY
                    Value: !Ref Memory
                  - !If
                    - UseGPU
                    - Type: GPU
                      Value: !Ref GPU
                    - !Ref "AWS::NoValue"

```
